name: prana
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # This section MUST be indented correctly.
  # 'assets:' should have two spaces before it.
  # The line below it should have four spaces.
  assets:
    - assets/images/

  fonts:
    - family: Cinzel
      fonts:
        - asset: fonts/Cinzel-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
